// <auto-generated />
namespace Motip.Web.AzureMobileService.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class InitMiggration : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(InitMiggration));
        
        string IMigrationMetadata.Id
        {
            get { return "201502161600554_InitMiggration"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
